Repository hobeetInc/hobeet, pull requests merged in 2024-11, with the labels that each got.

#28 Feat/#14/onetimeclub subpage
  src/app/(pages)/(club)/club/_api/supabase.ts
  src/app/(pages)/(club)/club/_components/oneTimeClub/MemberType.tsx
  src/app/(pages)/(club)/club/_components/regularClub/MemberType.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_types/Crews.ts
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_types/Crews.ts
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/RegularNotification.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/TabLayout.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_types/subCreate.ts
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/layout.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-time/RegularContent.tsx
  src/app/Header.tsx
Labels: enhancement

#33 build: pwa 수정 #32
  .gitignore
  public/icon512_maskable.png
  public/icon512_rounded.png
  public/manifest.json
  public/manifest.webmanifest
  public/sw.js
  public/workbox-1bb06f5e.js
Labels: enhancement

#36 feat: 검색기능 및 인기리스트 출력 #32
  public/asset/Icon/Frame 1000007052.png
  src/app/(pages)/(club)/club/_api/supabase.ts
  src/app/(pages)/(kakaopay)/kakaopay/paymentSummary/page.tsx
  src/app/(pages)/(search)/_api/supabase.ts
  src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
  src/app/(pages)/(search)/search/page.tsx
  src/app/Footer.tsx
  src/app/Header.tsx
  src/app/api/payment/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/OneTimeClubList.tsx
  src/components/RegularClubList.tsx
Labels: enhancement

#37 Feat/#29/mypage
  src/app/(pages)/(auth)/auth/callback/InsertUserInfo/page.tsx
  src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
  src/app/(pages)/(mypage)/_api/supabase.ts
  src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx
  src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
  src/app/(pages)/(mypage)/_components/logout.ts
  src/app/(pages)/(mypage)/mypage/paymentDetails/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/page.tsx
  src/app/(pages)/(mypage)/mypage/profileUpdate/page.tsx
  src/app/Footer.tsx
Labels: enhancement

#39 feat: 내가 찜한 모임 모아보기 구현 #29
  src/app/(pages)/(mypage)/_api/supabase.ts
  src/app/(pages)/(mypage)/mypage/profile/page.tsx
  src/app/(pages)/(mypage)/mypage/wishClubList/page.tsx
Labels: enhancement

#40 Feat/#30/club join kakaopay
  next.config.mjs
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(kakaopay)/kakaopay/_components/KakaopayBtn.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/api/oneTimeChatRoomRecruiterEntrance/route.ts
  src/app/api/oneTimeClubChattingRoom/route.ts
  src/app/api/payment/route.ts
  src/components/myclublistcontent/ClubListContent.tsx
  src/components/oneTimeClubJoinButton.tsx
  src/components/onetimeclublist/OneTimeClubCard.tsx
  src/components/regularclublist/RegularClubCard.tsx
  src/utils/onetimeclubjoin/_api/supabase.ts
  src/utils/onetimeclubjoin/join.ts
  src/utils/regularclubjoin/_api/supabase.ts
Labels: enhancement

#42 feat: 카테고리별 리스트 출력 기능 구현 #32
  src/app/(pages)/(categoryList)/_api/supabase.ts
  src/app/(pages)/(categoryList)/_components/CategoryList.tsx
  src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx
  src/app/Header.tsx
  src/components/CategorySlider.tsx
  src/components/RegularClubList.tsx
Labels: enhancement

#44 Feat/#29/mypage
  public/asset/Message-Filled.png
  public/asset/icon-google.png
  public/asset/icon-kakao.png
  src/app/(pages)/(auth)/signin/page.tsx
  src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/paymentSummary/page.tsx
  src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx
  src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
  src/app/(pages)/(mypage)/mypage/paymentDetails/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/page.tsx
Labels: enhancement

#43 Feat/#14/onetimeclub subpage
  public/asset/Icon/Heart-Outline.png
  src/app/(pages)/(club)/club/_api/supabase.ts
  src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx
  src/app/(pages)/(club)/club/_types/ClubForm.ts
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/WishListHeart.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
Labels: enhancement

#47 Feat/#14/onetimeclub subpage
  public/sw.js
  src/app/(pages)/(club)/club/_api/supabase.ts
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/PopHeader.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/DayHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_types/subCreate.ts
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
Labels: enhancement

#46 fix: 빌드에러 수정 #32
  public/sw.js
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/NotificationList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/_components/KakaopayBtn.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/paymentSummary/page.tsx
  src/app/(pages)/(mypage)/_api/supabase.ts
  src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx
  src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
  src/app/(pages)/(mypage)/mypage/wishClubList/page.tsx
  src/app/(pages)/(search)/_api/supabase.ts
  src/app/(pages)/(search)/search/page.tsx
  src/app/api/payment/route.ts
  src/components/RegularClubList.tsx
  tsconfig.json
Labels: enhancement

#48 Feat/#30/club join kakaopay
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/components/oneTimeClubJoinButton.tsx
  src/components/regularClubJoinButton.tsx
  src/utils/regularclubjoin/_api/supabase.ts
  src/utils/regularclubjoin/join.ts
Labels: enhancement

#50 Feat/#49/resolving club create error
  src/app/(pages)/(club)/club/_api/supabase.ts
  src/app/(pages)/(club)/club/_components/RegularClubList.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Category.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/NotificationList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/RegularNotification.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
Labels: enhancement

#51 fix:정기 모임 가입 승인/승인이 필요하지 않는 부분 로직 수정/#30
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/api/payment/route.ts
  src/app/approvemembers/page.tsx
  src/components/regularClubJoinButton.tsx
  src/utils/regularclubjoin/_api/supabase.ts
  src/utils/regularclubjoin/join.ts
Labels: enhancement

#52 Feat/#29/mypage
  public/sw.js
  src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/approvemembers/[id]/page.tsx
Labels: enhancement

#53 fix: 마이페이지 타입 오류 해결 #49
  public/sw.js
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/one-time/OneTimeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx
  src/app/(pages)/(mypage)/mypage/wishClubList/page.tsx
  src/utils/regularclubjoin/_api/supabase.ts
Labels: enhancement

#56 fix: 마이페이지 내가 결제한 목록 버그 수정 #55
  src/app/(pages)/(mypage)/_api/supabase.ts
  src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx
  src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
Labels: bug

#57 fix: secondId 값으로 수정 #49
  src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
Labels: bug

#60 Feat/#49/resolving club create error
  src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/MemberType.tsx
  src/app/(pages)/(club)/club/_components/regularClub/MemberType.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
Labels: bug, enhancement

#62 fix: 배포주소 변경 #58
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/api/payment/route.ts
Labels: documentation

#63 fix: 빌드 테스트 오류 해결 #58
  public/sw.js
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx
Labels: duplicate

#67 Feat/#30/club join kakaopay
  src/app/(pages)/(categoryList)/_api/supabase.ts
  src/app/(pages)/(chat)/chat/_components/OneTimeClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/_components/RegularClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/_components/ChatContext.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/page.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/_components/ChatContext.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/page.tsx
  src/app/(pages)/(club)/club/_api/supabase.ts
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/(pages)/(mypage)/_api/supabase.ts
  src/app/(pages)/(mypage)/mypage/wishClubList/page.tsx
  src/app/(pages)/(search)/_api/supabase.ts
  src/app/api/_ChatRoomExit/ChatRoomExit.tsx
  src/app/api/chatRoomApproveRecruiterEntrance/route.ts
  src/app/api/chatRoomMeetingPlace/route.ts
  src/app/api/chatRoomRecruiterEntrance/route.ts
  src/app/api/createChatRoom/route.ts
  src/app/api/createOneTimeChatRoom/route.ts
  src/app/api/getChatRoom/route.ts
  src/app/api/getOneTimeChatRoom/route.ts
  src/app/api/oneTimeChatRoomMeetingPlace/route.ts
  src/app/api/oneTimeChatRoomRecruiterEntrance/route.ts
  src/app/api/oneTimeClubChattingRoom/route.ts
  src/app/api/payment/route.ts
  src/app/api/regularClubChattingRoom/route.ts
  src/app/approvemembers/[id]/page.tsx
  src/app/onetimeclubjointest/page.tsx
  src/app/regularclubjointest/page.tsx
  src/components/myclublistcontent/_api/ClubListContentApi.ts
  src/components/onetimeclublist/OneTimeClubCard.tsx
  src/components/regularclublist/RegularClubCard.tsx
  src/utils/onetimeclubjoin/_api/supabase.ts
  src/utils/onetimeclubjoin/join.ts
  src/utils/regularclubjoin/_api/supabase.ts
Labels: enhancement

#68 Feat/#64/type separation
  public/sw.js
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/_components/ChatContext.tsx
  src/app/(pages)/(club)/club/_api/supabase.ts
Labels: enhancement

#77 Style/#72/my club list UI
  src/app/(pages)/(approvemembers)/approvemembers/[id]/page.tsx
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/(pages)/(myclublist)/myclublist/page.tsx
  src/app/api/payment/route.ts
  src/components/myclublistcontent/ClubListContent.tsx
  src/components/onetimeclublist/OneTimeClubCard.tsx
  src/components/regularclublist/RegularClubCard.tsx
  src/components/uiComponents/ApproveMemberTapBar.tsx
  src/components/uiComponents/TapBar.tsx
Labels: enhancement

#78 Style/#75/chat
  package.json
  public/asset/Icon/icon-vector.svg
  public/asset/eggsBanner.png
  src/app/(pages)/(chat)/chat/_components/OneTimeClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/_components/RegularClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/page.tsx
  src/app/(pages)/(chat)/chat/page.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/_components/ChatContext.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/page.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(mypage)/mypage/profile/page.tsx
  src/app/(pages)/(search)/_api/supabase.ts
  src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
  src/app/(pages)/(search)/search/page.tsx
  src/app/Footer.tsx
  src/app/Header.tsx
  src/app/api/getChatRoom/route.ts
  src/app/api/getOneTimeChatRoom/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/test/page.tsx
  src/components/CategorySlider.tsx
  src/components/OneTimeClubList.tsx
  src/components/RegularClubList.tsx
  src/components/uiComponents/HorizontalContentsListLarge.tsx
  src/components/uiComponents/HorizontalList.tsx
  src/components/uiComponents/LocationImage.tsx
  src/components/uiComponents/Tag.tsx
  src/components/uiComponents/Tag/Tag.tsx
  src/components/uiComponents/Text/Text.tsx
  src/components/uiComponents/VerticalContentsListMedium.tsx
  src/components/uiComponents/VerticalList.tsx
  src/components/uiComponents/icon/Icon.tsx
  src/components/uiComponents/icon/icons.tsx
  src/components/uiComponents/profileList.tsx
  src/components/uiComponents/text/index.tsx
  src/types/eggclubchat.types.ts
  src/types/eggpopchat.types.ts
  src/types/search.types.ts
  yarn.lock
Labels: enhancement

#79 build: 빌드오류 해결
  public/sw.js
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/components/uiComponents/profileList.tsx
Labels: bug

#80 Style/#75/chat
  public/sw.js
  src/app/(pages)/(chat)/chat/_components/OneTimeClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/_components/RegularClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/page.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/page.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
  src/app/(pages)/(search)/search/page.tsx
  src/app/Header.tsx
  src/app/test/page.tsx
  src/components/OneTimeClubJoinButtonCom.tsx
  src/components/RegularClubJoinButtonCom.tsx
  src/components/uiComponents/HorizontalList.tsx
  src/components/uiComponents/IconComponents/Icon.tsx
  src/components/uiComponents/IconComponents/Icons.tsx
  src/components/uiComponents/TagComponents/Tag.tsx
  src/components/uiComponents/TextComponents/Text.tsx
  src/components/uiComponents/VerticalContentsListMedium.tsx
  src/components/uiComponents/VerticalList.tsx
  src/components/uiComponents/profileList.tsx
  src/types/join.types.ts
Labels: bug

#81 Style/#76/club create page
  public/sw.js
  src/app/(pages)/(club)/club/_components/ProgressBar.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/AddressSearch.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Category.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/ClubTitle.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/ImageUpload.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Introduction.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/MemberType.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Tax.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/one-time/OneTimeContent.tsx
  src/app/(pages)/(club)/club/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-time/RegularContent.tsx
  src/app/test/page.tsx
  src/components/uiComponents/IconComponents/Icon.tsx
  src/components/uiComponents/Image/ImageUpload.tsx
  src/components/uiComponents/Input/ClubCreateInput.tsx
  src/components/uiComponents/Input/NumberSpinner.tsx
  src/components/uiComponents/Input/SearchInput.tsx
  src/components/uiComponents/Input/Textarea.tsx
  src/components/uiComponents/TagComponents/Tag.tsx
  src/components/uiComponents/VerticalList.tsx
  src/components/uiComponents/button/index.tsx
Labels: enhancement

#82 build: 빌드오류 해결
  public/sw.js
  src/app/(pages)/(club)/club/_components/oneTimeClub/AddressSearch.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Category.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Introduction.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/MemberType.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Tax.tsx
  src/app/(pages)/(club)/club/one-time/OneTimeContent.tsx
  src/app/(pages)/(club)/club/page.tsx
  src/components/uiComponents/Button/ButtonCom.tsx
  src/components/uiComponents/Input/NumberSpinner.tsx
Labels: bug

#85 style: 탐색쪽 스타일 적용 #75
  public/sw.js
  src/app/(pages)/(categoryList)/_api/supabase.ts
  src/app/(pages)/(categoryList)/_components/CategoryList.tsx
  src/app/(pages)/(categoryList)/category/[categoryId]/layout.tsx
  src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx
  src/app/(pages)/(chat)/chat/page.tsx
  src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
  src/app/(pages)/(search)/search/page.tsx
  src/app/Footer.tsx
  src/app/Header.tsx
  src/components/myclublistcontent/ClubListContent.tsx
  src/components/myclublistcontent/_api/ClubListContentApi.ts
  src/components/uiComponents/TapBar.tsx
  src/types/eggclubchat.types.ts
  src/types/search.types.ts
Labels: enhancement

#86 style: rootLayout 조건부 랜더링 #75
  src/app/(pages)/(auth)/signin/page.tsx
  src/app/(pages)/(categoryList)/_components/CategoryList.tsx
  src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/layout.tsx
  src/app/layout.tsx
  src/app/metadata.ts
  src/app/page.tsx
Labels: enhancement

#87 Style/#72/my club list UI
  src/app/(pages)/(approvemembers)/approvemembers/[id]/page.tsx
  src/app/Header.tsx
  src/app/layout.tsx
  src/components/myclublistcontent/ClubListContent.tsx
  src/components/onetimeclublist/OneTimeClubCard.tsx
  src/components/regularclublist/RegularClubCard.tsx
  src/components/uiComponents/ApproveMemberTapBar.tsx
  src/components/uiComponents/TapBar.tsx
Labels: enhancement

#88 Style/#75/chat
  public/asset/Bottom nav_Button_Search.png
  public/asset/Bottom nav_Button_Search_Default.png
  public/sw.js
  src/app/Header.tsx
  src/app/layout.tsx
Labels: enhancement

#90 Style/#76/club create page
  public/sw.js
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/PopHeader.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/NotificationList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/RegularNotification.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/DayHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
  src/components/OneTimeClubJoinButtonCom.tsx
  src/components/RegularClubJoinButtonCom.tsx
  src/components/uiComponents/Button/ButtonCom.tsx
  src/components/uiComponents/IconComponents/Icon.tsx
  src/components/uiComponents/IconComponents/Icons.tsx
  src/components/uiComponents/ProfileImageLarge.tsx
  src/types/eggclub.types.ts
Labels: enhancement

#91 style: Footer,layout Text컴포넌트 적용 및 불필요한 콘솔로그 삭제 #89
  src/app/(pages)/(categoryList)/category/[categoryId]/layout.tsx
  src/app/(pages)/(chat)/chat/_components/RegularClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/_components/ChatContext.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx
  src/app/Footer.tsx
  src/app/page.tsx
Labels: bug, enhancement

#92 style: 검색 인기 모임 리스트 margin값 변경 #89
  src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
Labels: bug

#93 build: 배포url 적용 #89
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/api/payment/route.ts
Labels: enhancement

#96 Feat/#89/egg pop detail
  src/app/(pages)/(categoryList)/category/[categoryId]/layout.tsx
  src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
  src/app/(pages)/(search)/search/page.tsx
  src/app/Footer.tsx
  src/app/Header.tsx
  src/app/api/payment/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/CategorySlider.tsx
  src/components/uiComponents/HorizontalList.tsx
  src/components/uiComponents/VerticalContentsListMedium.tsx
Labels: enhancement

#98 style: 디자인 수정 완료 #76
  package.json
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx
  src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
  src/app/(pages)/(mypage)/mypage/paymentDetails/page.tsx
  src/app/(pages)/(mypage)/mypage/wishClubList/page.tsx
  src/app/error.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/test/page.tsx
  src/components/RegularClubJoinButtonCom.tsx
  src/components/uiComponents/TapBar.tsx
  src/types/mypage.types.ts
  src/types/payment.types.ts
  yarn.lock
Labels: enhancement

#97 style: 회원가입 스타일 적용 및 프로필 수정 페이지 , 프로필 페이지 스타일 적용 #89
  public/sw.js
  src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
  src/app/(pages)/(auth)/signupSecond/_components/DateScrollPicker.tsx
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/page.tsx
  src/app/(pages)/(mypage)/mypage/profileUpdate/page.tsx
  src/app/Header.tsx
  src/app/api/payment/route.ts
  src/app/layout.tsx
Labels: enhancement

#99 style: 메인페이지 이미지 가운데 정렬안된 문제 해결 #89
  src/app/page.tsx
Labels: bug

#100 style: 미비된 디자인 적용 #89
  src/app/(pages)/(approvemembers)/approvemembers/[id]/page.tsx
  src/app/(pages)/(categoryList)/_components/CategoryList.tsx
  src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/api/payment/route.ts
  src/app/error.tsx
  src/app/layout.tsx
  src/components/uiComponents/VerticalContentsListLarge.tsx
Labels: enhancement

#106 Style/#76/club create page
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(club)/club/one-time/OneTimeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/DayHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
  src/app/(pages)/(club)/club/regular-time/RegularContent.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/api/payment/route.ts
  src/app/page.tsx
  src/utils/throttle.tsx/torottleCreateClub.tsx
Labels: enhancement

#107 fit: 카테고리페이지 버그 수정
  src/app/(pages)/(categoryList)/_components/CategoryList.tsx
  src/components/CategorySlider.tsx
Labels: bug

#108 fix: 유즈 파람 사용해서 뒤로가기 막기 수정 #76
  public/sw.js
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/DayHeader.tsx
Labels: bug, enhancement

#109 fix: 회원가입 프로필 이미지 크기 수정
  src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
Labels: bug

#104 해상도에 따라 조건부 컴포넌트 구현을 위해 store 생성
  src/app/store/useScreenSizeStore.ts
  src/components/uiComponents/ResponsiveDesign/ScreenSizeInitializer.tsx
Labels: enhancement

#110 fix: Link태그 a태그로 변경
  src/app/(pages)/(chat)/chat/_components/OneTimeClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/_components/RegularClubChattingRoomPage.tsx
Labels: bug

#111 fix: 결제 뒤로가기 막기 #76
  public/sw.js
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/PopHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/DayHeader.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/page.tsx
Labels: bug, enhancement

#112 Feat/#89/egg pop detail
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/api/payment/route.ts
  src/app/test/page.tsx
  src/utils/onetimeclubjoin/_api/supabase.ts
Labels: bug

#115 fix: 뒤로가기 막기 성공......#76
  src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/PopHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
Labels: bug

#116 fix: 버그 수정
  src/app/(pages)/(chat)/_components/oneTimeClub/OneTimeClubChatRoomRecruiterEntrance.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/NotificationList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/api/payment/route.ts
  src/app/page.tsx
Labels: bug

#118 fix: 카테고리 스크롤 생성
  src/app/(pages)/(club)/club/_components/oneTimeClub/Category.tsx
  src/app/(pages)/(club)/club/_components/regularClub/Category.tsx
Labels: bug

#120 fix: 카테고리 무한 api 호출 문제 해결
  src/app/(pages)/(categoryList)/category/[categoryId]/layout.tsx
Labels: bug

#122 add: sentry 설정
  .gitignore
  next.config.mjs
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/api/sentry-example-api/route.ts
  src/app/global-error.tsx
  src/app/sentry-example-page/page.tsx
  src/instrumentation.ts
  yarn.lock
Labels: enhancement

#123 feat: 카카오톡 이미지 못불러오는거 오류 고침 #121
  next.config.mjs
Labels: enhancement

#130 Style/#125/css qa ty
  public/asset/Category icon_airplane.png
  public/asset/Category icon_clapper-board.png
  src/app/(pages)/(chat)/_api/onetime.ts
  src/app/(pages)/(chat)/chat/_pages/OneTimeClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/_pages/RegularClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/_components/ChatContext.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/isSuccess/page.tsx
  src/app/_components/CategorySlider.tsx
  src/app/api/payment/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/uiComponents/IconComponents/Icon.tsx
  src/components/uiComponents/IconComponents/Icons.tsx
  src/components/uiComponents/VerticalContentsListMedium.tsx
Labels: enhancement

#132 모임 상세페이지 디자인 수정
  public/asset/smallBanner.svg
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/NotificationList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
  src/app/(pages)/(search)/search/page.tsx
  src/components/layout/Header.tsx
Labels: enhancement

#131 Style/#124/css qa jm
  .env.sentry-build-plugin
  src/app/(pages)/(categoryList)/category/[categoryId]/layout.tsx
  src/app/(pages)/(club)/club/list/onetime/page.tsx
  src/app/(pages)/(club)/club/list/regular/page.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/FullScreenModal.tsx
  src/app/sentry-example-page/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: enhancement

#139 Refactor/#135/jm
  src/app/sentry-example-page/page.tsx
  src/types/global.d.ts
Labels: 리팩토링

#133 Style/#124/css qa jm
  bun.lockb
  database.types.ts
  database.types.ts.zip
  public/sw.js
  public/sw.js.map
  public/workbox-1bb06f5e.js
  public/workbox-1bb06f5e.js.map
  src/app/(pages)/(categoryList)/category/[categoryId]/layout.tsx
  yarn.lock
Labels: 스타일, 개발

#145 Style/#141/css qa jh
  src/app/(pages)/(categoryList)/category/[categoryId]/layout.tsx
  src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx
  src/components/uiComponents/ResponsiveDesign/ScreenSizeInitializer.tsx
  src/store/useScreenSizeStore.ts
Labels: 스타일, 리팩토링

#146 style: 채팅방 바텀 마진 변경 #125
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/page.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/page.tsx
Labels: 스타일

#147 Refactor/#136/sh
  public/asset/defaultProfileImg.svg
  src/app/(pages)/(auth)/_api/fetchUser.ts
  src/app/(pages)/(auth)/_api/logOut.ts
  src/app/(pages)/(auth)/_api/updateUser.ts
  src/app/(pages)/(auth)/_api/uploadProfile.ts
  src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/_api/fetchClub.ts
  src/app/(pages)/(kakaopay)/kakaopay/_api/fetchPayment.ts
  src/app/(pages)/(kakaopay)/kakaopay/_api/fetchPaymentClub.ts
  src/app/(pages)/(kakaopay)/kakaopay/_api/kakaoPayment.ts
  src/app/(pages)/(kakaopay)/kakaopay/_components/KakaopayBtn.tsx
  src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/(pages)/(mypage)/_api/fecthMyPayList.ts
  src/app/(pages)/(mypage)/_api/fetchProfile.ts
  src/app/(pages)/(mypage)/_api/fetchWishList.ts
  src/app/(pages)/(mypage)/_api/logout.ts
  src/app/(pages)/(mypage)/_api/profileEdit.ts
  src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx
  src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
  src/app/(pages)/(mypage)/_components/logout.ts
  src/app/(pages)/(mypage)/mypage/inquiry/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/page.tsx
  src/app/(pages)/(mypage)/mypage/profileUpdate/page.tsx
  src/app/(pages)/(mypage)/mypage/wishClubList/page.tsx
  src/app/api/payment/_service/getClubPaymentInfo.ts
  src/app/api/payment/_service/kakaoPayment.ts
  src/app/api/payment/_service/savePaymentInfo.ts
  src/app/api/payment/route.ts
  src/types/payment.types.ts
  src/utils/CustomDate.ts
  src/utils/signup/birthDate.ts
  src/utils/signup/validation.ts
Labels: 리팩토링

#148 Refactor/#135/jm
  src/app/(pages)/(approvemembers)/approvemembers/[id]/page.tsx
  src/app/(pages)/(club)/club/_api/clubSubmission.ts
  src/app/(pages)/(club)/club/_api/members.ts
  src/app/(pages)/(club)/club/_api/notifications.ts
  src/app/(pages)/(club)/club/_api/wishlist.ts
  src/app/(pages)/(club)/club/_components/OneTimeClubList.tsx
  src/app/(pages)/(club)/club/_components/RegularClubList.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/AddressSearch.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Category.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Introduction.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/MemberType.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Tax.tsx
  src/app/(pages)/(club)/club/_components/regularClub/ApplicationMethod.tsx
  src/app/(pages)/(club)/club/_components/regularClub/Category.tsx
  src/app/(pages)/(club)/club/_components/regularClub/Introduction.tsx
  src/app/(pages)/(club)/club/_components/regularClub/MemberType.tsx
  src/app/(pages)/(club)/club/list/onetime/page.tsx
  src/app/(pages)/(club)/club/list/regular/page.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/PopHeader.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/one-time/_components/OneTimeContent.tsx
  src/app/(pages)/(club)/club/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/NotificationList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/RegularNotification.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/TabLayout.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/WishListHeart.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/DayHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-time/RegularContent.tsx
  src/app/_components/OneTimeClubList.tsx
  src/app/api/cardList.ts
  src/components/uiComponents/HorizontalList.tsx
  src/components/uiComponents/VerticalList.tsx
  src/hooks/eggPopQueries.ts
  src/hooks/useClubWishlist.ts
  src/hooks/useCreate.ts
  src/hooks/useUploadImage.ts
  src/hooks/utils/queryKeys.ts
  src/types/common.types.ts
  src/types/eggclub.types.ts
  src/types/eggday.types.ts
  src/types/eggpop.types.ts
  src/types/user.types.ts
  src/types/안끝난거/eggclub.types.ts
  src/types/안끝난거/eggday.types.ts
Labels: 리팩토링

#152 Refactor/#135/jm
  public/sw.js
  public/sw.js.map
  public/workbox-1bb06f5e.js
  public/workbox-1bb06f5e.js.map
  src/app/(pages)/(approvemembers)/approvemembers/[id]/page.tsx
  src/app/(pages)/(chat)/_api/onetime.ts
  src/app/(pages)/(chat)/chat/_pages/OneTimeClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/_pages/RegularClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/_components/ChatContext.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(club)/club/_api/clubSubmission.ts
  src/app/(pages)/(club)/club/_api/members.ts
  src/app/(pages)/(club)/club/_components/oneTimeClub/Category.tsx
  src/app/(pages)/(club)/club/_components/regularClub/Category.tsx
  src/app/(pages)/(club)/club/list/onetime/page.tsx
  src/app/(pages)/(club)/club/list/regular/page.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/one-time/_components/OneTimeContent.tsx
  src/app/(pages)/(club)/club/one-time/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/WishListHeart.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/page.tsx
  src/app/(pages)/(club)/club/regular-time/RegularContent.tsx
  src/app/(pages)/(club)/club/regular-time/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/_api/fetchPayment.ts
  src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/(pages)/(myclublist)/myclublist/_components/ClubListContent.tsx
  src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx
  src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
  src/app/(pages)/(mypage)/mypage/profile/page.tsx
  src/app/(pages)/(mypage)/mypage/profileUpdate/page.tsx
  src/app/(pages)/(mypage)/mypage/wishClubList/page.tsx
  src/app/(pages)/(search)/search/page.tsx
  src/app/(pages)/testPage/page.tsx
  src/app/_components/OneTimeClubList.tsx
  src/app/_components/RegularClubList.tsx
  src/app/api/cardList.ts
  src/hooks/eggPopQueries.ts
  src/hooks/index.ts
  src/hooks/useCreate.ts
  src/hooks/useKakaopayRequest.ts
  src/hooks/useMyWishlist.ts
  src/hooks/usePayment.ts
  src/hooks/useProfile.ts
  src/hooks/utils/list/allList.ts
  src/hooks/utils/list/tenList.ts
  src/hooks/utils/list/useClubWishlist.ts
  src/hooks/utils/queryKeys.ts
  src/types/eggpop.types.ts
  src/types/eggpopchat.types.ts
  src/types/user.types.ts
  src/types/안끝난거/eggpop.types.ts
Labels: 리팩토링

#151 Refactor/#134/ty
  next.config.mjs
  package.json
  public/sw.js
  src/app/(pages)/(chat)/chat/_pages/OneTimeClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/_pages/RegularClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/_components/ChatInput.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/page.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/_components/ChatContext.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/_components/ChatInput.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/page.tsx
  src/app/(pages)/(search)/_api/supabase.ts
  src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
  src/app/layout.tsx
  src/components/uiComponents/HorizontalContentsListLarge.tsx
  src/components/uiComponents/HorizontalList.tsx
  src/types/search.types.ts
  yarn.lock
Labels: 리팩토링

#154 Refactor/#136/sh
  public/asset/AppIcon.svg
  src/app/(pages)/(auth)/auth/callback/InsertUserInfo/page.tsx
  src/app/(pages)/(auth)/auth/callback/route.ts
  src/app/(pages)/(auth)/signin/page.tsx
  src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
  src/app/(pages)/(categoryList)/_components/CategoryList.tsx
  src/app/(pages)/(kakaopay)/kakaopay/_components/KakaopayBtn.tsx
  src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx
  src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
  src/app/(pages)/(mypage)/mypage/inquiry/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/inquiry/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/paymentDetails/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/profileUpdate/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/wishClubList/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/utils/supabase/middleware.ts
Labels: 리팩토링

#155 Refactor/#135/jm
  public/sw.js
  public/sw.js.map
  src/app/(pages)/(club)/club/_components/oneTimeClub/AddressSearch.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/MemberType.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Tax.tsx
  src/app/(pages)/(club)/club/_components/regularClub/MemberType.tsx
  src/app/(pages)/(club)/club/_utils/formatter.ts
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/PopHeader.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/one-time/_components/OneTimeContent.tsx
  src/app/(pages)/(club)/club/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/DayHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-time/RegularContent.tsx
  src/app/(pages)/(club)/club/regular-time/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/_components/KakaopayBtn.tsx
  src/app/(pages)/(search)/search/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/uiComponents/Input/NumberSpinner.tsx
  src/components/uiComponents/Input/SearchInput.tsx
  src/hooks/useOneTimeChat.ts
  src/hooks/utils/list/crewList.ts
  src/hooks/utils/queryKeys.ts
Labels: 스타일

#153 fix:에그팝,에그클럽 참여하기 버튼 zustand로 getUser로직 수정/#138
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/OneTimeClubJoinButtonCom.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/RegularClubJoinButtonCom.tsx
  src/app/(pages)/(myclublist)/myclublist/page.tsx
Labels: 리팩토링

#159 Refactor/#135/jm
  src/app/(pages)/(categoryList)/_api/supabase.ts
  src/app/(pages)/(categoryList)/category/[categoryId]/page.tsx
  src/app/(pages)/(chat)/_api/supabase.ts
  src/app/(pages)/(club)/club/_components/OneTimeClubList.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/PopHeader.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/WishListHeart.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/DayHeader.tsx
  src/app/api/sentry-example-api/route.ts
  src/app/sentry-example-page/page.tsx
Labels: 리팩토링

#166 Style/#165/qa2 jm
  README.md
  public/sw.js
  public/sw.js.map
  public/workbox-f1770938.js
  public/workbox-f1770938.js.map
  src/app/(pages)/(chat)/chat/page.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Category.tsx
  src/app/(pages)/(club)/club/_components/regularClub/Category.tsx
  src/app/(pages)/(club)/club/_utils/localStorage.ts
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/PopHeader.tsx
  src/app/(pages)/(club)/club/one-time/_components/OneTimeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/DayHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/AddressSearch.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/DateTime.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/Introduction.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/Tax.tsx
  src/app/(pages)/(club)/club/regular-time/RegularContent.tsx
  src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
  src/app/_components/CategorySlider.tsx
  src/app/_components/ProgressBar.tsx
  src/app/page.tsx
  src/hooks/utils/api/useCreate.ts
  src/hooks/utils/list/eggdayList.ts
  src/types/features/club/eggday.types.ts
  supabase/.temp/cli-latest
Labels: 스타일

#172 Refactor/#171/props driling
  public/sw.js
  public/sw.js.map
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/NotificationList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/RegularNotification.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/StoreInitializer.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
  src/app/sentry-example-page/page.tsx
  src/store/crewStore.tsx
Labels: 리팩토링

#173 Style/105/responsive web design
  src/app/(pages)/(chat)/chat/_pages/OneTimeClubChattingRoomPage.tsx
  src/app/(pages)/(chat)/chat/_pages/RegularClubChattingRoomPage.tsx
  src/app/layout.tsx
  src/components/uiComponents/molecules/navigation/TapBar.tsx
  src/components/uiComponents/responsiveDesign/ScreenSizeInitializer.tsx
  src/store/useScreenSizeStore.ts
Labels: 스타일
