Repository hobeetInc/hobeet, pull requests merged in 2024-12, with the labels that each got.

#175 Style/#174/responsive web design/club subpage
  public/sw.js
  public/sw.js.map
  src/app/(pages)/(club)/club/_components/FloatingButton.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/RegularClubJoinButtonCom.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/TabLayout.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
  src/app/layout.tsx
  src/components/layout/FloatingButton.tsx
  src/components/layout/Footer.tsx
  src/components/layout/index.ts
  src/components/uiComponents/atoms/buttons/ButtonCom.tsx
  src/components/uiComponents/atoms/icons/Icon.tsx
  src/components/uiComponents/atoms/icons/Icons.tsx
  src/components/uiComponents/molecules/navigation/ApproveMemberTapBar.tsx
Labels: 스타일

#176 Style/#174/responsive web design/club subpage
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/TabLayout.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/FullScreenModal.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/page.tsx
  src/app/_components/FloatingButton.tsx
Labels: 스타일

#177 Style/105/모임 생성 선택 모달창 작업
  public/sw.js
  public/sw.js.map
  src/app/(pages)/(club)/club/one-time/_components/OneTimeContent.tsx
  src/app/(pages)/(club)/club/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
  src/app/(pages)/(club)/club/regular-time/RegularContent.tsx
  src/components/uiComponents/responsiveDesign/Modal.tsx
  src/utils/throttle/throttleCreateClub.tsx
  tsconfig.json
Labels: 스타일, 리팩토링

#178 Yarn Berry 설정 추가 및 의존성 업데이트, 클럽 리스트 컴포넌트 리팩토링
  .gitignore
  .pnp.cjs
  .pnp.loader.mjs
  .vscode/extensions.json
  .vscode/settings.json
  .yarn/releases/yarn-4.5.3.cjs
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/lib/unsupported-api.js
  .yarn/sdks/eslint/package.json
  .yarn/sdks/integrations.yml
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  .yarn/sdks/typescript/package.json
  .yarnrc.yml
  package.json
  public/sw.js
  public/sw.js.map
  public/workbox-b4dc1f0a.js
  public/workbox-f1770938.js.map
  src/app/(pages)/(auth)/signin/page.tsx
  src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
  src/app/(pages)/(club)/club/_components/OneTimeClubList.tsx
  src/app/(pages)/(club)/club/_components/RegularClubList.tsx
  src/app/(pages)/(mypage)/mypage/profile/page.tsx
  src/components/uiComponents/atoms/buttons/ButtonCom.tsx
  tsconfig.json
  yarn.lock
Labels: 리팩토링

#179 Style/#174/responsive web design/club subpage
  .gitignore
  .pnp.cjs
  .yarn/releases/yarn-4.5.3.cjs
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarnrc.yml
  package.json
  public/sw.js
  public/workbox-829af5f8.js
  src/app/(pages)/(approvemembers)/approvemembers/_components/ApproveModal.tsx
  src/app/(pages)/(approvemembers)/approvemembers/_components/PendingRequestsTab.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/CrewList.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/RegularClubJoinButtonCom.tsx
  tsconfig.json
  yarn.lock
Labels: 리팩토링

#182 Style/105/responsive web design
  public/sw.js
  src/app/(pages)/(club)/club/_components/oneTimeClub/AddressSearch.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Category.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/DateTime.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/MemberType.tsx
  src/app/(pages)/(club)/club/_components/oneTimeClub/Tax.tsx
  src/app/(pages)/(club)/club/_components/regularClub/Category.tsx
  src/app/(pages)/(club)/club/_components/regularClub/MemberType.tsx
  src/app/(pages)/(club)/club/one-time/_components/OneTimeContent.tsx
  src/app/(pages)/(club)/club/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubHeader.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/AddressSearch.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/DateTime.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/NotificationCreate.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/_components/Tax.tsx
  src/app/(pages)/(club)/club/regular-time/RegularContent.tsx
  src/app/_components/ProgressBar.tsx
  src/components/ui/atoms/Inputs/ClubCreateInput.tsx
  src/components/ui/atoms/Inputs/SearchInput.tsx
  src/components/ui/atoms/Inputs/Textarea.tsx
  src/components/ui/atoms/buttons/ButtonCom.tsx
  src/components/ui/responsiveDesign/Modal.tsx
Labels: 스타일, 개발

#183 feat: 로딩 스피너 컴포넌트 추가 및 로딩 UX 개선
  public/asset/Icon/LoadingIcon.svg
  public/sw.js
  src/app/_components/CategorySlider.tsx
  src/app/_components/OneTimeClubList.tsx
  src/app/_components/RegularClubList.tsx
  src/app/loading.tsx
  src/components/ui/atoms/LoadingSpinner.tsx
Labels: 스타일, 개발

#185 Refactor/#138/jh
  .pnp.cjs
  .yarn/releases/yarn-4.5.3.cjs
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  package.json
  public/sw.js
  public/workbox-b4dc1f0a.js
  src/app/(pages)/(myclublist)/myclublist/_components/ClubListContent.tsx
  src/components/ui/organisms/lists/BigVerticalContentsList.tsx
  tsconfig.json
  yarn.lock
Labels: 스타일

#184 Style/#174/responsive web design/club subpage
  public/asset/Banner/banner1.svg
  public/asset/Banner/banner2.svg
  public/asset/Banner/banner3.svg
  public/sw.js
  src/app/(pages)/(club)/club/list/onetime/page.tsx
  src/app/(pages)/(club)/club/list/regular/page.tsx
  src/app/_components/RegularClubList.tsx
  src/app/page.tsx
Labels: 스타일

#190 Style/#174/responsive web design/club subpage
  public/asset/Banner/smallWebBanner.svg
  public/sw.js
  src/app/(pages)/(club)/club/list/onetime/page.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/PopHeader.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/page.tsx
  src/app/(pages)/(search)/_api/supabase.ts
  src/app/(pages)/(search)/_components/OverallPopularMeetings.tsx
  src/app/(pages)/(search)/search/page.tsx
  src/components/layout/FloatingButton.tsx
  src/components/layout/Header.tsx
  src/components/ui/organisms/lists/BigHorizontalContentsList.tsx
  src/types/utils/search.types.ts
Labels: 스타일

#192 style: 메인 더보기 호버 추가
  public/sw.js
  src/app/page.tsx
Labels: 스타일

#191 마이페이지, 결제 전/후 페이지 반응형 작업
  .pnp.cjs
  next.config.mjs
  src/app/(pages)/(auth)/signin/page.tsx
  src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/_components/KakaopayBtn.tsx
  src/app/(pages)/(kakaopay)/kakaopay/paymentConfirm/page.tsx
  src/app/(pages)/(kakaopay)/kakaopay/success/page.tsx
  src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx
  src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
  src/app/(pages)/(mypage)/mypage/profile/inquiry/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/paymentDetails/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/profileUpdate/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/wishClubList/page.tsx
Labels: 스타일

#193 Style/#174/responsive web design/club subpage
  .pnp.cjs
  public/sw.js
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/RegularClubJoinButtonCom.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/page.tsx
  src/app/(pages)/(mypage)/_components/eggDayPayDetail.tsx
  src/app/(pages)/(mypage)/_components/eggPopPayDetail.tsx
  src/app/(pages)/(mypage)/mypage/profile/inquiry/page.tsx
  src/app/(pages)/(mypage)/mypage/profile/wishClubList/page.tsx
  src/app/_components/OneTimeClubList.tsx
Labels: 스타일

#194 Style/#174/responsive web design/club subpage
  public/sw.js
  src/app/(pages)/(auth)/signupSecond/[userId]/page.tsx
  src/app/(pages)/(club)/club/list/onetime/page.tsx
  src/app/(pages)/(club)/club/list/regular/page.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/ClubCard.tsx
Labels: 버그

#195 Style/105/responsive web design
  next.config.mjs
  public/sw.js
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/_components/ChatInput.tsx
  src/app/(pages)/(chat)/chat/onetimeChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/_components/ChatInput.tsx
  src/app/(pages)/(chat)/chat/regularChat/[chatRoomId]/layout.tsx
  src/app/(pages)/(club)/club/one-time-club-sub/[id]/_components/EggPopImage.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/_components/HomeContent.tsx
  src/app/(pages)/(club)/club/regular-club-sub/[id]/create/[subId]/_components/DayImage.tsx
  src/app/_components/OneTimeClubList.tsx
  src/app/_components/RegularClubList.tsx
  src/app/_components/banners/ChristmasBanner.tsx
  src/app/_components/skeletons/LoadingSkeleton.tsx
  src/app/_components/skeletons/OneTimeClubSkeleton.tsx
  src/app/_components/skeletons/RegularClubSkeleton.tsx
  src/app/page.tsx
  src/components/ui/atoms/Skeleton.tsx
Labels: 스타일, 리팩토링
